// <auto-generated />
using HotelListing.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    partial class HotelListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alpha2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Alpha3")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha2 = "AF",
                            Alpha3 = "AFG",
                            Name = "Afghanistan",
                            NumericCode = "0004"
                        },
                        new
                        {
                            Id = 2,
                            Alpha2 = "AL",
                            Alpha3 = "ALB",
                            Name = "Albania",
                            NumericCode = "0008"
                        },
                        new
                        {
                            Id = 3,
                            Alpha2 = "DZ",
                            Alpha3 = "DZA",
                            Name = "Algeria",
                            NumericCode = "0012"
                        },
                        new
                        {
                            Id = 4,
                            Alpha2 = "AS",
                            Alpha3 = "ASM",
                            Name = "American Samoa",
                            NumericCode = "0016"
                        },
                        new
                        {
                            Id = 5,
                            Alpha2 = "AD",
                            Alpha3 = "AND",
                            Name = "Andorra",
                            NumericCode = "0020"
                        },
                        new
                        {
                            Id = 6,
                            Alpha2 = "AO",
                            Alpha3 = "AGO",
                            Name = "Angola",
                            NumericCode = "0024"
                        },
                        new
                        {
                            Id = 7,
                            Alpha2 = "AI",
                            Alpha3 = "AIA",
                            Name = "Anguilla",
                            NumericCode = "0660"
                        },
                        new
                        {
                            Id = 8,
                            Alpha2 = "AQ",
                            Alpha3 = "ATA",
                            Name = "Antarctica",
                            NumericCode = "0010"
                        },
                        new
                        {
                            Id = 9,
                            Alpha2 = "AG",
                            Alpha3 = "ATG",
                            Name = "Antigua and Barbuda",
                            NumericCode = "0028"
                        },
                        new
                        {
                            Id = 10,
                            Alpha2 = "AR",
                            Alpha3 = "ARG",
                            Name = "Argentina",
                            NumericCode = "0032"
                        },
                        new
                        {
                            Id = 11,
                            Alpha2 = "AM",
                            Alpha3 = "ARM",
                            Name = "Armenia",
                            NumericCode = "0051"
                        },
                        new
                        {
                            Id = 12,
                            Alpha2 = "AW",
                            Alpha3 = "ABW",
                            Name = "Aruba",
                            NumericCode = "0533"
                        },
                        new
                        {
                            Id = 13,
                            Alpha2 = "AU",
                            Alpha3 = "AUS",
                            Name = "Australia",
                            NumericCode = "0036"
                        },
                        new
                        {
                            Id = 14,
                            Alpha2 = "AT",
                            Alpha3 = "AUT",
                            Name = "Austria",
                            NumericCode = "0040"
                        },
                        new
                        {
                            Id = 15,
                            Alpha2 = "AZ",
                            Alpha3 = "AZE",
                            Name = "Azerbaijan",
                            NumericCode = "0031"
                        },
                        new
                        {
                            Id = 16,
                            Alpha2 = "BS",
                            Alpha3 = "BHS",
                            Name = "Bahamas (the)",
                            NumericCode = "0044"
                        },
                        new
                        {
                            Id = 17,
                            Alpha2 = "BH",
                            Alpha3 = "BHR",
                            Name = "Bahrain",
                            NumericCode = "0048"
                        },
                        new
                        {
                            Id = 18,
                            Alpha2 = "BD",
                            Alpha3 = "BGD",
                            Name = "Bangladesh",
                            NumericCode = "0050"
                        },
                        new
                        {
                            Id = 19,
                            Alpha2 = "BB",
                            Alpha3 = "BRB",
                            Name = "Barbados",
                            NumericCode = "0052"
                        },
                        new
                        {
                            Id = 20,
                            Alpha2 = "BY",
                            Alpha3 = "BLR",
                            Name = "Belarus",
                            NumericCode = "0112"
                        },
                        new
                        {
                            Id = 21,
                            Alpha2 = "BE",
                            Alpha3 = "BEL",
                            Name = "Belgium",
                            NumericCode = "0056"
                        },
                        new
                        {
                            Id = 22,
                            Alpha2 = "BZ",
                            Alpha3 = "BLZ",
                            Name = "Belize",
                            NumericCode = "0084"
                        },
                        new
                        {
                            Id = 23,
                            Alpha2 = "BJ",
                            Alpha3 = "BEN",
                            Name = "Benin",
                            NumericCode = "0204"
                        },
                        new
                        {
                            Id = 24,
                            Alpha2 = "BM",
                            Alpha3 = "BMU",
                            Name = "Bermuda",
                            NumericCode = "0060"
                        },
                        new
                        {
                            Id = 25,
                            Alpha2 = "BT",
                            Alpha3 = "BTN",
                            Name = "Bhutan",
                            NumericCode = "0064"
                        },
                        new
                        {
                            Id = 26,
                            Alpha2 = "BO",
                            Alpha3 = "BOL",
                            Name = "Bolivia (Plurinational State of)",
                            NumericCode = "0068"
                        },
                        new
                        {
                            Id = 27,
                            Alpha2 = "BQ",
                            Alpha3 = "BES",
                            Name = "Bonaire, Sint Eustatius and Saba",
                            NumericCode = "0535"
                        },
                        new
                        {
                            Id = 28,
                            Alpha2 = "BA",
                            Alpha3 = "BIH",
                            Name = "Bosnia and Herzegovina",
                            NumericCode = "0070"
                        },
                        new
                        {
                            Id = 29,
                            Alpha2 = "BW",
                            Alpha3 = "BWA",
                            Name = "Botswana",
                            NumericCode = "0072"
                        },
                        new
                        {
                            Id = 30,
                            Alpha2 = "BV",
                            Alpha3 = "BVT",
                            Name = "Bouvet Island",
                            NumericCode = "0074"
                        },
                        new
                        {
                            Id = 31,
                            Alpha2 = "BR",
                            Alpha3 = "BRA",
                            Name = "Brazil",
                            NumericCode = "0076"
                        },
                        new
                        {
                            Id = 32,
                            Alpha2 = "IO",
                            Alpha3 = "IOT",
                            Name = "British Indian Ocean Territory (the)",
                            NumericCode = "0086"
                        },
                        new
                        {
                            Id = 33,
                            Alpha2 = "BN",
                            Alpha3 = "BRN",
                            Name = "Brunei Darussalam",
                            NumericCode = "0096"
                        },
                        new
                        {
                            Id = 34,
                            Alpha2 = "BG",
                            Alpha3 = "BGR",
                            Name = "Bulgaria",
                            NumericCode = "0100"
                        },
                        new
                        {
                            Id = 35,
                            Alpha2 = "BF",
                            Alpha3 = "BFA",
                            Name = "Burkina Faso",
                            NumericCode = "0854"
                        },
                        new
                        {
                            Id = 36,
                            Alpha2 = "BI",
                            Alpha3 = "BDI",
                            Name = "Burundi",
                            NumericCode = "0108"
                        },
                        new
                        {
                            Id = 37,
                            Alpha2 = "CV",
                            Alpha3 = "CPV",
                            Name = "Cabo Verde",
                            NumericCode = "0132"
                        },
                        new
                        {
                            Id = 38,
                            Alpha2 = "KH",
                            Alpha3 = "KHM",
                            Name = "Cambodia",
                            NumericCode = "0116"
                        },
                        new
                        {
                            Id = 39,
                            Alpha2 = "CM",
                            Alpha3 = "CMR",
                            Name = "Cameroon",
                            NumericCode = "0120"
                        },
                        new
                        {
                            Id = 40,
                            Alpha2 = "CA",
                            Alpha3 = "CAN",
                            Name = "Canada",
                            NumericCode = "0124"
                        },
                        new
                        {
                            Id = 41,
                            Alpha2 = "KY",
                            Alpha3 = "CYM",
                            Name = "Cayman Islands (the)",
                            NumericCode = "0136"
                        },
                        new
                        {
                            Id = 42,
                            Alpha2 = "CF",
                            Alpha3 = "CAF",
                            Name = "Central African Republic (the)",
                            NumericCode = "0140"
                        },
                        new
                        {
                            Id = 43,
                            Alpha2 = "TD",
                            Alpha3 = "TCD",
                            Name = "Chad",
                            NumericCode = "0148"
                        },
                        new
                        {
                            Id = 44,
                            Alpha2 = "CL",
                            Alpha3 = "CHL",
                            Name = "Chile",
                            NumericCode = "0152"
                        },
                        new
                        {
                            Id = 45,
                            Alpha2 = "CN",
                            Alpha3 = "CHN",
                            Name = "China",
                            NumericCode = "0156"
                        },
                        new
                        {
                            Id = 46,
                            Alpha2 = "CX",
                            Alpha3 = "CXR",
                            Name = "Christmas Island",
                            NumericCode = "0162"
                        },
                        new
                        {
                            Id = 47,
                            Alpha2 = "CC",
                            Alpha3 = "CCK",
                            Name = "Cocos (Keeling) Islands (the)",
                            NumericCode = "0166"
                        },
                        new
                        {
                            Id = 48,
                            Alpha2 = "CO",
                            Alpha3 = "COL",
                            Name = "Colombia",
                            NumericCode = "0170"
                        },
                        new
                        {
                            Id = 49,
                            Alpha2 = "KM",
                            Alpha3 = "COM",
                            Name = "Comoros (the)",
                            NumericCode = "0174"
                        },
                        new
                        {
                            Id = 50,
                            Alpha2 = "CD",
                            Alpha3 = "COD",
                            Name = "Congo (the Democratic Republic of the)",
                            NumericCode = "0180"
                        },
                        new
                        {
                            Id = 51,
                            Alpha2 = "CG",
                            Alpha3 = "COG",
                            Name = "Congo (the)",
                            NumericCode = "0178"
                        },
                        new
                        {
                            Id = 52,
                            Alpha2 = "CK",
                            Alpha3 = "COK",
                            Name = "Cook Islands (the)",
                            NumericCode = "0184"
                        },
                        new
                        {
                            Id = 53,
                            Alpha2 = "CR",
                            Alpha3 = "CRI",
                            Name = "Costa Rica",
                            NumericCode = "0188"
                        },
                        new
                        {
                            Id = 54,
                            Alpha2 = "HR",
                            Alpha3 = "HRV",
                            Name = "Croatia",
                            NumericCode = "0191"
                        },
                        new
                        {
                            Id = 55,
                            Alpha2 = "CU",
                            Alpha3 = "CUB",
                            Name = "Cuba",
                            NumericCode = "0192"
                        },
                        new
                        {
                            Id = 56,
                            Alpha2 = "CW",
                            Alpha3 = "CUW",
                            Name = "Curaçao",
                            NumericCode = "0531"
                        },
                        new
                        {
                            Id = 57,
                            Alpha2 = "CY",
                            Alpha3 = "CYP",
                            Name = "Cyprus",
                            NumericCode = "0196"
                        },
                        new
                        {
                            Id = 58,
                            Alpha2 = "CZ",
                            Alpha3 = "CZE",
                            Name = "Czechia",
                            NumericCode = "0203"
                        },
                        new
                        {
                            Id = 59,
                            Alpha2 = "CI",
                            Alpha3 = "CIV",
                            Name = "Côte d'Ivoire",
                            NumericCode = "0384"
                        },
                        new
                        {
                            Id = 60,
                            Alpha2 = "DK",
                            Alpha3 = "DNK",
                            Name = "Denmark",
                            NumericCode = "0208"
                        },
                        new
                        {
                            Id = 61,
                            Alpha2 = "DJ",
                            Alpha3 = "DJI",
                            Name = "Djibouti",
                            NumericCode = "0262"
                        },
                        new
                        {
                            Id = 62,
                            Alpha2 = "DM",
                            Alpha3 = "DMA",
                            Name = "Dominica",
                            NumericCode = "0212"
                        },
                        new
                        {
                            Id = 63,
                            Alpha2 = "DO",
                            Alpha3 = "DOM",
                            Name = "Dominican Republic (the)",
                            NumericCode = "0214"
                        },
                        new
                        {
                            Id = 64,
                            Alpha2 = "EC",
                            Alpha3 = "ECU",
                            Name = "Ecuador",
                            NumericCode = "0218"
                        },
                        new
                        {
                            Id = 65,
                            Alpha2 = "EG",
                            Alpha3 = "EGY",
                            Name = "Egypt",
                            NumericCode = "0818"
                        },
                        new
                        {
                            Id = 66,
                            Alpha2 = "SV",
                            Alpha3 = "SLV",
                            Name = "El Salvador",
                            NumericCode = "0222"
                        },
                        new
                        {
                            Id = 67,
                            Alpha2 = "GQ",
                            Alpha3 = "GNQ",
                            Name = "Equatorial Guinea",
                            NumericCode = "0226"
                        },
                        new
                        {
                            Id = 68,
                            Alpha2 = "ER",
                            Alpha3 = "ERI",
                            Name = "Eritrea",
                            NumericCode = "0232"
                        },
                        new
                        {
                            Id = 69,
                            Alpha2 = "EE",
                            Alpha3 = "EST",
                            Name = "Estonia",
                            NumericCode = "0233"
                        },
                        new
                        {
                            Id = 70,
                            Alpha2 = "SZ",
                            Alpha3 = "SWZ",
                            Name = "Eswatini",
                            NumericCode = "0748"
                        },
                        new
                        {
                            Id = 71,
                            Alpha2 = "ET",
                            Alpha3 = "ETH",
                            Name = "Ethiopia",
                            NumericCode = "0231"
                        },
                        new
                        {
                            Id = 72,
                            Alpha2 = "FK",
                            Alpha3 = "FLK",
                            Name = "Falkland Islands (the) [Malvinas]",
                            NumericCode = "0238"
                        },
                        new
                        {
                            Id = 73,
                            Alpha2 = "FO",
                            Alpha3 = "FRO",
                            Name = "Faroe Islands (the)",
                            NumericCode = "0234"
                        },
                        new
                        {
                            Id = 74,
                            Alpha2 = "FJ",
                            Alpha3 = "FJI",
                            Name = "Fiji",
                            NumericCode = "0242"
                        },
                        new
                        {
                            Id = 75,
                            Alpha2 = "FI",
                            Alpha3 = "FIN",
                            Name = "Finland",
                            NumericCode = "0246"
                        },
                        new
                        {
                            Id = 76,
                            Alpha2 = "FR",
                            Alpha3 = "FRA",
                            Name = "France",
                            NumericCode = "0250"
                        },
                        new
                        {
                            Id = 77,
                            Alpha2 = "GF",
                            Alpha3 = "GUF",
                            Name = "French Guiana",
                            NumericCode = "0254"
                        },
                        new
                        {
                            Id = 78,
                            Alpha2 = "PF",
                            Alpha3 = "PYF",
                            Name = "French Polynesia",
                            NumericCode = "0258"
                        },
                        new
                        {
                            Id = 79,
                            Alpha2 = "TF",
                            Alpha3 = "ATF",
                            Name = "French Southern Territories (the)",
                            NumericCode = "0260"
                        },
                        new
                        {
                            Id = 80,
                            Alpha2 = "GA",
                            Alpha3 = "GAB",
                            Name = "Gabon",
                            NumericCode = "0266"
                        },
                        new
                        {
                            Id = 81,
                            Alpha2 = "GM",
                            Alpha3 = "GMB",
                            Name = "Gambia (the)",
                            NumericCode = "0270"
                        },
                        new
                        {
                            Id = 82,
                            Alpha2 = "GE",
                            Alpha3 = "GEO",
                            Name = "Georgia",
                            NumericCode = "0268"
                        },
                        new
                        {
                            Id = 83,
                            Alpha2 = "DE",
                            Alpha3 = "DEU",
                            Name = "Germany",
                            NumericCode = "0276"
                        },
                        new
                        {
                            Id = 84,
                            Alpha2 = "GH",
                            Alpha3 = "GHA",
                            Name = "Ghana",
                            NumericCode = "0288"
                        },
                        new
                        {
                            Id = 85,
                            Alpha2 = "GI",
                            Alpha3 = "GIB",
                            Name = "Gibraltar",
                            NumericCode = "0292"
                        },
                        new
                        {
                            Id = 86,
                            Alpha2 = "GR",
                            Alpha3 = "GRC",
                            Name = "Greece",
                            NumericCode = "0300"
                        },
                        new
                        {
                            Id = 87,
                            Alpha2 = "GL",
                            Alpha3 = "GRL",
                            Name = "Greenland",
                            NumericCode = "0304"
                        },
                        new
                        {
                            Id = 88,
                            Alpha2 = "GD",
                            Alpha3 = "GRD",
                            Name = "Grenada",
                            NumericCode = "0308"
                        },
                        new
                        {
                            Id = 89,
                            Alpha2 = "GP",
                            Alpha3 = "GLP",
                            Name = "Guadeloupe",
                            NumericCode = "0312"
                        },
                        new
                        {
                            Id = 90,
                            Alpha2 = "GU",
                            Alpha3 = "GUM",
                            Name = "Guam",
                            NumericCode = "0316"
                        },
                        new
                        {
                            Id = 91,
                            Alpha2 = "GT",
                            Alpha3 = "GTM",
                            Name = "Guatemala",
                            NumericCode = "0320"
                        },
                        new
                        {
                            Id = 92,
                            Alpha2 = "GG",
                            Alpha3 = "GGY",
                            Name = "Guernsey",
                            NumericCode = "0831"
                        },
                        new
                        {
                            Id = 93,
                            Alpha2 = "GN",
                            Alpha3 = "GIN",
                            Name = "Guinea",
                            NumericCode = "0324"
                        },
                        new
                        {
                            Id = 94,
                            Alpha2 = "GW",
                            Alpha3 = "GNB",
                            Name = "Guinea-Bissau",
                            NumericCode = "0624"
                        },
                        new
                        {
                            Id = 95,
                            Alpha2 = "GY",
                            Alpha3 = "GUY",
                            Name = "Guyana",
                            NumericCode = "0328"
                        },
                        new
                        {
                            Id = 96,
                            Alpha2 = "HT",
                            Alpha3 = "HTI",
                            Name = "Haiti",
                            NumericCode = "0332"
                        },
                        new
                        {
                            Id = 97,
                            Alpha2 = "HM",
                            Alpha3 = "HMD",
                            Name = "Heard Island and McDonald Islands",
                            NumericCode = "0334"
                        },
                        new
                        {
                            Id = 98,
                            Alpha2 = "VA",
                            Alpha3 = "VAT",
                            Name = "Holy See (the)",
                            NumericCode = "0336"
                        },
                        new
                        {
                            Id = 99,
                            Alpha2 = "HN",
                            Alpha3 = "HND",
                            Name = "Honduras",
                            NumericCode = "0340"
                        },
                        new
                        {
                            Id = 100,
                            Alpha2 = "HK",
                            Alpha3 = "HKG",
                            Name = "Hong Kong",
                            NumericCode = "0344"
                        },
                        new
                        {
                            Id = 101,
                            Alpha2 = "HU",
                            Alpha3 = "HUN",
                            Name = "Hungary",
                            NumericCode = "0348"
                        },
                        new
                        {
                            Id = 102,
                            Alpha2 = "IS",
                            Alpha3 = "ISL",
                            Name = "Iceland",
                            NumericCode = "0352"
                        },
                        new
                        {
                            Id = 103,
                            Alpha2 = "IN",
                            Alpha3 = "IND",
                            Name = "India",
                            NumericCode = "0356"
                        },
                        new
                        {
                            Id = 104,
                            Alpha2 = "ID",
                            Alpha3 = "IDN",
                            Name = "Indonesia",
                            NumericCode = "0360"
                        },
                        new
                        {
                            Id = 105,
                            Alpha2 = "IR",
                            Alpha3 = "IRN",
                            Name = "Iran (Islamic Republic of)",
                            NumericCode = "0364"
                        },
                        new
                        {
                            Id = 106,
                            Alpha2 = "IQ",
                            Alpha3 = "IRQ",
                            Name = "Iraq",
                            NumericCode = "0368"
                        },
                        new
                        {
                            Id = 107,
                            Alpha2 = "IE",
                            Alpha3 = "IRL",
                            Name = "Ireland",
                            NumericCode = "0372"
                        },
                        new
                        {
                            Id = 108,
                            Alpha2 = "IM",
                            Alpha3 = "IMN",
                            Name = "Isle of Man",
                            NumericCode = "0833"
                        },
                        new
                        {
                            Id = 109,
                            Alpha2 = "IL",
                            Alpha3 = "ISR",
                            Name = "Israel",
                            NumericCode = "0376"
                        },
                        new
                        {
                            Id = 110,
                            Alpha2 = "IT",
                            Alpha3 = "ITA",
                            Name = "Italy",
                            NumericCode = "0380"
                        },
                        new
                        {
                            Id = 111,
                            Alpha2 = "JM",
                            Alpha3 = "JAM",
                            Name = "Jamaica",
                            NumericCode = "0388"
                        },
                        new
                        {
                            Id = 112,
                            Alpha2 = "JP",
                            Alpha3 = "JPN",
                            Name = "Japan",
                            NumericCode = "0392"
                        },
                        new
                        {
                            Id = 113,
                            Alpha2 = "JE",
                            Alpha3 = "JEY",
                            Name = "Jersey",
                            NumericCode = "0832"
                        },
                        new
                        {
                            Id = 114,
                            Alpha2 = "JO",
                            Alpha3 = "JOR",
                            Name = "Jordan",
                            NumericCode = "0400"
                        },
                        new
                        {
                            Id = 115,
                            Alpha2 = "KZ",
                            Alpha3 = "KAZ",
                            Name = "Kazakhstan",
                            NumericCode = "0398"
                        },
                        new
                        {
                            Id = 116,
                            Alpha2 = "KE",
                            Alpha3 = "KEN",
                            Name = "Kenya",
                            NumericCode = "0404"
                        },
                        new
                        {
                            Id = 117,
                            Alpha2 = "KI",
                            Alpha3 = "KIR",
                            Name = "Kiribati",
                            NumericCode = "0296"
                        },
                        new
                        {
                            Id = 118,
                            Alpha2 = "KP",
                            Alpha3 = "PRK",
                            Name = "Korea (the Democratic People's Republic of)",
                            NumericCode = "0408"
                        },
                        new
                        {
                            Id = 119,
                            Alpha2 = "KR",
                            Alpha3 = "KOR",
                            Name = "Korea (the Republic of)",
                            NumericCode = "0410"
                        },
                        new
                        {
                            Id = 120,
                            Alpha2 = "KW",
                            Alpha3 = "KWT",
                            Name = "Kuwait",
                            NumericCode = "0414"
                        },
                        new
                        {
                            Id = 121,
                            Alpha2 = "KG",
                            Alpha3 = "KGZ",
                            Name = "Kyrgyzstan",
                            NumericCode = "0417"
                        },
                        new
                        {
                            Id = 122,
                            Alpha2 = "LA",
                            Alpha3 = "LAO",
                            Name = "Lao People's Democratic Republic(the)",
                            NumericCode = "0418"
                        },
                        new
                        {
                            Id = 123,
                            Alpha2 = "LV",
                            Alpha3 = "LVA",
                            Name = "Latvia",
                            NumericCode = "0428"
                        },
                        new
                        {
                            Id = 124,
                            Alpha2 = "LB",
                            Alpha3 = "LBN",
                            Name = "Lebanon",
                            NumericCode = "0422"
                        },
                        new
                        {
                            Id = 125,
                            Alpha2 = "LS",
                            Alpha3 = "LSO",
                            Name = "Lesotho",
                            NumericCode = "0426"
                        },
                        new
                        {
                            Id = 126,
                            Alpha2 = "LR",
                            Alpha3 = "LBR",
                            Name = "Liberia",
                            NumericCode = "0430"
                        },
                        new
                        {
                            Id = 127,
                            Alpha2 = "LY",
                            Alpha3 = "LBY",
                            Name = "Libya",
                            NumericCode = "0434"
                        },
                        new
                        {
                            Id = 128,
                            Alpha2 = "LI",
                            Alpha3 = "LIE",
                            Name = "Liechtenstein",
                            NumericCode = "0438"
                        },
                        new
                        {
                            Id = 129,
                            Alpha2 = "LT",
                            Alpha3 = "LTU",
                            Name = "Lithuania",
                            NumericCode = "0440"
                        },
                        new
                        {
                            Id = 130,
                            Alpha2 = "LU",
                            Alpha3 = "LUX",
                            Name = "Luxembourg",
                            NumericCode = "0442"
                        },
                        new
                        {
                            Id = 131,
                            Alpha2 = "MO",
                            Alpha3 = "MAC",
                            Name = "Macao",
                            NumericCode = "0446"
                        },
                        new
                        {
                            Id = 132,
                            Alpha2 = "MG",
                            Alpha3 = "MDG",
                            Name = "Madagascar",
                            NumericCode = "0450"
                        },
                        new
                        {
                            Id = 133,
                            Alpha2 = "MW",
                            Alpha3 = "MWI",
                            Name = "Malawi",
                            NumericCode = "0454"
                        },
                        new
                        {
                            Id = 134,
                            Alpha2 = "MY",
                            Alpha3 = "MYS",
                            Name = "Malaysia",
                            NumericCode = "0458"
                        },
                        new
                        {
                            Id = 135,
                            Alpha2 = "MV",
                            Alpha3 = "MDV",
                            Name = "Maldives",
                            NumericCode = "0462"
                        },
                        new
                        {
                            Id = 136,
                            Alpha2 = "ML",
                            Alpha3 = "MLI",
                            Name = "Mali",
                            NumericCode = "0466"
                        },
                        new
                        {
                            Id = 137,
                            Alpha2 = "MT",
                            Alpha3 = "MLT",
                            Name = "Malta",
                            NumericCode = "0470"
                        },
                        new
                        {
                            Id = 138,
                            Alpha2 = "MH",
                            Alpha3 = "MHL",
                            Name = "Marshall Islands (the)",
                            NumericCode = "0584"
                        },
                        new
                        {
                            Id = 139,
                            Alpha2 = "MQ",
                            Alpha3 = "MTQ",
                            Name = "Martinique",
                            NumericCode = "0474"
                        },
                        new
                        {
                            Id = 140,
                            Alpha2 = "MR",
                            Alpha3 = "MRT",
                            Name = "Mauritania",
                            NumericCode = "0478"
                        },
                        new
                        {
                            Id = 141,
                            Alpha2 = "MU",
                            Alpha3 = "MUS",
                            Name = "Mauritius",
                            NumericCode = "0480"
                        },
                        new
                        {
                            Id = 142,
                            Alpha2 = "YT",
                            Alpha3 = "MYT",
                            Name = "Mayotte",
                            NumericCode = "0175"
                        },
                        new
                        {
                            Id = 143,
                            Alpha2 = "MX",
                            Alpha3 = "MEX",
                            Name = "Mexico",
                            NumericCode = "0484"
                        },
                        new
                        {
                            Id = 144,
                            Alpha2 = "FM",
                            Alpha3 = "FSM",
                            Name = "Micronesia (Federated States of)",
                            NumericCode = "0583"
                        },
                        new
                        {
                            Id = 145,
                            Alpha2 = "MD",
                            Alpha3 = "MDA",
                            Name = "Moldova (the Republic of)",
                            NumericCode = "0498"
                        },
                        new
                        {
                            Id = 146,
                            Alpha2 = "MC",
                            Alpha3 = "MCO",
                            Name = "Monaco",
                            NumericCode = "0492"
                        },
                        new
                        {
                            Id = 147,
                            Alpha2 = "MN",
                            Alpha3 = "MNG",
                            Name = "Mongolia",
                            NumericCode = "0496"
                        },
                        new
                        {
                            Id = 148,
                            Alpha2 = "ME",
                            Alpha3 = "MNE",
                            Name = "Montenegro",
                            NumericCode = "0499"
                        },
                        new
                        {
                            Id = 149,
                            Alpha2 = "MS",
                            Alpha3 = "MSR",
                            Name = "Montserrat",
                            NumericCode = "0500"
                        },
                        new
                        {
                            Id = 150,
                            Alpha2 = "MA",
                            Alpha3 = "MAR",
                            Name = "Morocco",
                            NumericCode = "0504"
                        },
                        new
                        {
                            Id = 151,
                            Alpha2 = "MZ",
                            Alpha3 = "MOZ",
                            Name = "Mozambique",
                            NumericCode = "0508"
                        },
                        new
                        {
                            Id = 152,
                            Alpha2 = "MM",
                            Alpha3 = "MMR",
                            Name = "Myanmar",
                            NumericCode = "0104"
                        },
                        new
                        {
                            Id = 153,
                            Alpha2 = "NA",
                            Alpha3 = "NAM",
                            Name = "Namibia",
                            NumericCode = "0516"
                        },
                        new
                        {
                            Id = 154,
                            Alpha2 = "NR",
                            Alpha3 = "NRU",
                            Name = "Nauru",
                            NumericCode = "0520"
                        },
                        new
                        {
                            Id = 155,
                            Alpha2 = "NP",
                            Alpha3 = "NPL",
                            Name = "Nepal",
                            NumericCode = "0524"
                        },
                        new
                        {
                            Id = 156,
                            Alpha2 = "NL",
                            Alpha3 = "NLD",
                            Name = "Netherlands (the)",
                            NumericCode = "0528"
                        },
                        new
                        {
                            Id = 157,
                            Alpha2 = "NC",
                            Alpha3 = "NCL",
                            Name = "New Caledonia",
                            NumericCode = "0540"
                        },
                        new
                        {
                            Id = 158,
                            Alpha2 = "NZ",
                            Alpha3 = "NZL",
                            Name = "New Zealand",
                            NumericCode = "0554"
                        },
                        new
                        {
                            Id = 159,
                            Alpha2 = "NI",
                            Alpha3 = "NIC",
                            Name = "Nicaragua",
                            NumericCode = "0558"
                        },
                        new
                        {
                            Id = 160,
                            Alpha2 = "NE",
                            Alpha3 = "NER",
                            Name = "Niger (the)",
                            NumericCode = "0562"
                        },
                        new
                        {
                            Id = 161,
                            Alpha2 = "NG",
                            Alpha3 = "NGA",
                            Name = "Nigeria",
                            NumericCode = "0566"
                        },
                        new
                        {
                            Id = 162,
                            Alpha2 = "NU",
                            Alpha3 = "NIU",
                            Name = "Niue",
                            NumericCode = "0570"
                        },
                        new
                        {
                            Id = 163,
                            Alpha2 = "NF",
                            Alpha3 = "NFK",
                            Name = "Norfolk Island",
                            NumericCode = "0574"
                        },
                        new
                        {
                            Id = 164,
                            Alpha2 = "MP",
                            Alpha3 = "MNP",
                            Name = "Northern Mariana Islands (the)",
                            NumericCode = "0580"
                        },
                        new
                        {
                            Id = 165,
                            Alpha2 = "NO",
                            Alpha3 = "NOR",
                            Name = "Norway",
                            NumericCode = "0578"
                        },
                        new
                        {
                            Id = 166,
                            Alpha2 = "OM",
                            Alpha3 = "OMN",
                            Name = "Oman",
                            NumericCode = "0512"
                        },
                        new
                        {
                            Id = 167,
                            Alpha2 = "PK",
                            Alpha3 = "PAK",
                            Name = "Pakistan",
                            NumericCode = "0586"
                        },
                        new
                        {
                            Id = 168,
                            Alpha2 = "PW",
                            Alpha3 = "PLW",
                            Name = "Palau",
                            NumericCode = "0585"
                        },
                        new
                        {
                            Id = 169,
                            Alpha2 = "PS",
                            Alpha3 = "PSE",
                            Name = "Palestine, State of",
                            NumericCode = "0275"
                        },
                        new
                        {
                            Id = 170,
                            Alpha2 = "PA",
                            Alpha3 = "PAN",
                            Name = "Panama",
                            NumericCode = "0591"
                        },
                        new
                        {
                            Id = 171,
                            Alpha2 = "PG",
                            Alpha3 = "PNG",
                            Name = "Papua New Guinea",
                            NumericCode = "0598"
                        },
                        new
                        {
                            Id = 172,
                            Alpha2 = "PY",
                            Alpha3 = "PRY",
                            Name = "Paraguay",
                            NumericCode = "0600"
                        },
                        new
                        {
                            Id = 173,
                            Alpha2 = "PE",
                            Alpha3 = "PER",
                            Name = "Peru",
                            NumericCode = "0604"
                        },
                        new
                        {
                            Id = 174,
                            Alpha2 = "PH",
                            Alpha3 = "PHL",
                            Name = "Philippines (the)",
                            NumericCode = "0608"
                        },
                        new
                        {
                            Id = 175,
                            Alpha2 = "PN",
                            Alpha3 = "PCN",
                            Name = "Pitcairn",
                            NumericCode = "0612"
                        },
                        new
                        {
                            Id = 176,
                            Alpha2 = "PL",
                            Alpha3 = "POL",
                            Name = "Poland",
                            NumericCode = "0616"
                        },
                        new
                        {
                            Id = 177,
                            Alpha2 = "PT",
                            Alpha3 = "PRT",
                            Name = "Portugal",
                            NumericCode = "0620"
                        },
                        new
                        {
                            Id = 178,
                            Alpha2 = "PR",
                            Alpha3 = "PRI",
                            Name = "Puerto Rico",
                            NumericCode = "0630"
                        },
                        new
                        {
                            Id = 179,
                            Alpha2 = "QA",
                            Alpha3 = "QAT",
                            Name = "Qatar",
                            NumericCode = "0634"
                        },
                        new
                        {
                            Id = 180,
                            Alpha2 = "MK",
                            Alpha3 = "MKD",
                            Name = "Republic of North Macedonia",
                            NumericCode = "0807"
                        },
                        new
                        {
                            Id = 181,
                            Alpha2 = "RO",
                            Alpha3 = "ROU",
                            Name = "Romania",
                            NumericCode = "0642"
                        },
                        new
                        {
                            Id = 182,
                            Alpha2 = "RU",
                            Alpha3 = "RUS",
                            Name = "Russian Federation (the)",
                            NumericCode = "0643"
                        },
                        new
                        {
                            Id = 183,
                            Alpha2 = "RW",
                            Alpha3 = "RWA",
                            Name = "Rwanda",
                            NumericCode = "0646"
                        },
                        new
                        {
                            Id = 184,
                            Alpha2 = "RE",
                            Alpha3 = "REU",
                            Name = "Réunion",
                            NumericCode = "0638"
                        },
                        new
                        {
                            Id = 185,
                            Alpha2 = "BL",
                            Alpha3 = "BLM",
                            Name = "Saint Barthélemy",
                            NumericCode = "0652"
                        },
                        new
                        {
                            Id = 186,
                            Alpha2 = "SH",
                            Alpha3 = "SHN",
                            Name = "Saint Helena, Ascension and Tristan da Cunha",
                            NumericCode = "0654"
                        },
                        new
                        {
                            Id = 187,
                            Alpha2 = "KN",
                            Alpha3 = "KNA",
                            Name = "Saint Kitts and Nevis",
                            NumericCode = "0659"
                        },
                        new
                        {
                            Id = 188,
                            Alpha2 = "LC",
                            Alpha3 = "LCA",
                            Name = "Saint Lucia",
                            NumericCode = "0662"
                        },
                        new
                        {
                            Id = 189,
                            Alpha2 = "MF",
                            Alpha3 = "MAF",
                            Name = "Saint Martin (French part)",
                            NumericCode = "0663"
                        },
                        new
                        {
                            Id = 190,
                            Alpha2 = "PM",
                            Alpha3 = "SPM",
                            Name = "Saint Pierre and Miquelon",
                            NumericCode = "0666"
                        },
                        new
                        {
                            Id = 191,
                            Alpha2 = "VC",
                            Alpha3 = "VCT",
                            Name = "Saint Vincent and the Grenadines",
                            NumericCode = "0670"
                        },
                        new
                        {
                            Id = 192,
                            Alpha2 = "WS",
                            Alpha3 = "WSM",
                            Name = "Samoa",
                            NumericCode = "0882"
                        },
                        new
                        {
                            Id = 193,
                            Alpha2 = "SM",
                            Alpha3 = "SMR",
                            Name = "San Marino",
                            NumericCode = "0674"
                        },
                        new
                        {
                            Id = 194,
                            Alpha2 = "ST",
                            Alpha3 = "STP",
                            Name = "Sao Tome and Principe",
                            NumericCode = "0678"
                        },
                        new
                        {
                            Id = 195,
                            Alpha2 = "SA",
                            Alpha3 = "SAU",
                            Name = "Saudi Arabia",
                            NumericCode = "0682"
                        },
                        new
                        {
                            Id = 196,
                            Alpha2 = "SN",
                            Alpha3 = "SEN",
                            Name = "Senegal",
                            NumericCode = "0686"
                        },
                        new
                        {
                            Id = 197,
                            Alpha2 = "RS",
                            Alpha3 = "SRB",
                            Name = "Serbia",
                            NumericCode = "0688"
                        },
                        new
                        {
                            Id = 198,
                            Alpha2 = "SC",
                            Alpha3 = "SYC",
                            Name = "Seychelles",
                            NumericCode = "0690"
                        },
                        new
                        {
                            Id = 199,
                            Alpha2 = "SL",
                            Alpha3 = "SLE",
                            Name = "Sierra Leone",
                            NumericCode = "0694"
                        },
                        new
                        {
                            Id = 200,
                            Alpha2 = "SG",
                            Alpha3 = "SGP",
                            Name = "Singapore",
                            NumericCode = "0702"
                        },
                        new
                        {
                            Id = 201,
                            Alpha2 = "SX",
                            Alpha3 = "SXM",
                            Name = "Sint Maarten (Dutch part)",
                            NumericCode = "0534"
                        },
                        new
                        {
                            Id = 202,
                            Alpha2 = "SK",
                            Alpha3 = "SVK",
                            Name = "Slovakia",
                            NumericCode = "0703"
                        },
                        new
                        {
                            Id = 203,
                            Alpha2 = "SI",
                            Alpha3 = "SVN",
                            Name = "Slovenia",
                            NumericCode = "0705"
                        },
                        new
                        {
                            Id = 204,
                            Alpha2 = "SB",
                            Alpha3 = "SLB",
                            Name = "Solomon Islands",
                            NumericCode = "0090"
                        },
                        new
                        {
                            Id = 205,
                            Alpha2 = "SO",
                            Alpha3 = "SOM",
                            Name = "Somalia",
                            NumericCode = "0706"
                        },
                        new
                        {
                            Id = 206,
                            Alpha2 = "ZA",
                            Alpha3 = "ZAF",
                            Name = "South Africa",
                            NumericCode = "0710"
                        },
                        new
                        {
                            Id = 207,
                            Alpha2 = "GS",
                            Alpha3 = "SGS",
                            Name = "South Georgia and the South Sandwich Islands",
                            NumericCode = "0239"
                        },
                        new
                        {
                            Id = 208,
                            Alpha2 = "SS",
                            Alpha3 = "SSD",
                            Name = "South Sudan",
                            NumericCode = "0728"
                        },
                        new
                        {
                            Id = 209,
                            Alpha2 = "ES",
                            Alpha3 = "ESP",
                            Name = "Spain",
                            NumericCode = "0724"
                        },
                        new
                        {
                            Id = 210,
                            Alpha2 = "LK",
                            Alpha3 = "LKA",
                            Name = "Sri Lanka",
                            NumericCode = "0144"
                        },
                        new
                        {
                            Id = 211,
                            Alpha2 = "SD",
                            Alpha3 = "SDN",
                            Name = "Sudan (the)",
                            NumericCode = "0729"
                        },
                        new
                        {
                            Id = 212,
                            Alpha2 = "SR",
                            Alpha3 = "SUR",
                            Name = "Suriname",
                            NumericCode = "0740"
                        },
                        new
                        {
                            Id = 213,
                            Alpha2 = "SJ",
                            Alpha3 = "SJM",
                            Name = "Svalbard and Jan Mayen",
                            NumericCode = "0744"
                        },
                        new
                        {
                            Id = 214,
                            Alpha2 = "SE",
                            Alpha3 = "SWE",
                            Name = "Sweden",
                            NumericCode = "0752"
                        },
                        new
                        {
                            Id = 215,
                            Alpha2 = "CH",
                            Alpha3 = "CHE",
                            Name = "Switzerland",
                            NumericCode = "0756"
                        },
                        new
                        {
                            Id = 216,
                            Alpha2 = "SY",
                            Alpha3 = "SYR",
                            Name = "Syrian Arab Republic",
                            NumericCode = "0760"
                        },
                        new
                        {
                            Id = 217,
                            Alpha2 = "TW",
                            Alpha3 = "TWN",
                            Name = "Taiwan (Province of China)",
                            NumericCode = "0158"
                        },
                        new
                        {
                            Id = 218,
                            Alpha2 = "TJ",
                            Alpha3 = "TJK",
                            Name = "Tajikistan",
                            NumericCode = "0762"
                        },
                        new
                        {
                            Id = 219,
                            Alpha2 = "TZ",
                            Alpha3 = "TZA",
                            Name = "Tanzania, United Republic of",
                            NumericCode = "0834"
                        },
                        new
                        {
                            Id = 220,
                            Alpha2 = "TH",
                            Alpha3 = "THA",
                            Name = "Thailand",
                            NumericCode = "0764"
                        },
                        new
                        {
                            Id = 221,
                            Alpha2 = "TL",
                            Alpha3 = "TLS",
                            Name = "Timor-Leste",
                            NumericCode = "0626"
                        },
                        new
                        {
                            Id = 222,
                            Alpha2 = "TG",
                            Alpha3 = "TGO",
                            Name = "Togo",
                            NumericCode = "0768"
                        },
                        new
                        {
                            Id = 223,
                            Alpha2 = "TK",
                            Alpha3 = "TKL",
                            Name = "Tokelau",
                            NumericCode = "0772"
                        },
                        new
                        {
                            Id = 224,
                            Alpha2 = "TO",
                            Alpha3 = "TON",
                            Name = "Tonga",
                            NumericCode = "0776"
                        },
                        new
                        {
                            Id = 225,
                            Alpha2 = "TT",
                            Alpha3 = "TTO",
                            Name = "Trinidad and Tobago",
                            NumericCode = "0780"
                        },
                        new
                        {
                            Id = 226,
                            Alpha2 = "TN",
                            Alpha3 = "TUN",
                            Name = "Tunisia",
                            NumericCode = "0788"
                        },
                        new
                        {
                            Id = 227,
                            Alpha2 = "TR",
                            Alpha3 = "TUR",
                            Name = "Turkey",
                            NumericCode = "0792"
                        },
                        new
                        {
                            Id = 228,
                            Alpha2 = "TM",
                            Alpha3 = "TKM",
                            Name = "Turkmenistan",
                            NumericCode = "0795"
                        },
                        new
                        {
                            Id = 229,
                            Alpha2 = "TC",
                            Alpha3 = "TCA",
                            Name = "Turks and Caicos Islands (the)",
                            NumericCode = "0796"
                        },
                        new
                        {
                            Id = 230,
                            Alpha2 = "TV",
                            Alpha3 = "TUV",
                            Name = "Tuvalu",
                            NumericCode = "0798"
                        },
                        new
                        {
                            Id = 231,
                            Alpha2 = "UG",
                            Alpha3 = "UGA",
                            Name = "Uganda",
                            NumericCode = "0800"
                        },
                        new
                        {
                            Id = 232,
                            Alpha2 = "UA",
                            Alpha3 = "UKR",
                            Name = "Ukraine",
                            NumericCode = "0804"
                        },
                        new
                        {
                            Id = 233,
                            Alpha2 = "AE",
                            Alpha3 = "ARE",
                            Name = "United Arab Emirates (the)",
                            NumericCode = "0784"
                        },
                        new
                        {
                            Id = 234,
                            Alpha2 = "GB",
                            Alpha3 = "GBR",
                            Name = "United Kingdom of Great Britain and Northern Ireland (the)",
                            NumericCode = "0826"
                        },
                        new
                        {
                            Id = 235,
                            Alpha2 = "UM",
                            Alpha3 = "UMI",
                            Name = "United States Minor Outlying Islands (the)",
                            NumericCode = "0581"
                        },
                        new
                        {
                            Id = 236,
                            Alpha2 = "US",
                            Alpha3 = "USA",
                            Name = "United States of America (the)",
                            NumericCode = "0840"
                        },
                        new
                        {
                            Id = 237,
                            Alpha2 = "UY",
                            Alpha3 = "URY",
                            Name = "Uruguay",
                            NumericCode = "0858"
                        },
                        new
                        {
                            Id = 238,
                            Alpha2 = "UZ",
                            Alpha3 = "UZB",
                            Name = "Uzbekistan",
                            NumericCode = "0860"
                        },
                        new
                        {
                            Id = 239,
                            Alpha2 = "VU",
                            Alpha3 = "VUT",
                            Name = "Vanuatu",
                            NumericCode = "0548"
                        },
                        new
                        {
                            Id = 240,
                            Alpha2 = "VE",
                            Alpha3 = "VEN",
                            Name = "Venezuela (Bolivarian Republic of)",
                            NumericCode = "0862"
                        },
                        new
                        {
                            Id = 241,
                            Alpha2 = "VN",
                            Alpha3 = "VNM",
                            Name = "Viet Nam",
                            NumericCode = "0704"
                        },
                        new
                        {
                            Id = 242,
                            Alpha2 = "VG",
                            Alpha3 = "VGB",
                            Name = "Virgin Islands (British)",
                            NumericCode = "0092"
                        },
                        new
                        {
                            Id = 243,
                            Alpha2 = "VI",
                            Alpha3 = "VIR",
                            Name = "Virgin Islands (U.S.)",
                            NumericCode = "0850"
                        },
                        new
                        {
                            Id = 244,
                            Alpha2 = "WF",
                            Alpha3 = "WLF",
                            Name = "Wallis and Futuna",
                            NumericCode = "0876"
                        },
                        new
                        {
                            Id = 245,
                            Alpha2 = "EH",
                            Alpha3 = "ESH",
                            Name = "Western Sahara",
                            NumericCode = "0732"
                        },
                        new
                        {
                            Id = 246,
                            Alpha2 = "YE",
                            Alpha3 = "YEM",
                            Name = "Yemen",
                            NumericCode = "0887"
                        },
                        new
                        {
                            Id = 247,
                            Alpha2 = "ZM",
                            Alpha3 = "ZMB",
                            Name = "Zambia",
                            NumericCode = "0894"
                        },
                        new
                        {
                            Id = 248,
                            Alpha2 = "ZW",
                            Alpha3 = "ZWE",
                            Name = "Zimbabwe",
                            NumericCode = "0716"
                        },
                        new
                        {
                            Id = 249,
                            Alpha2 = "AX",
                            Alpha3 = "ALA",
                            Name = "Åland Islands",
                            NumericCode = "0248"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "James St",
                            CountryId = 19,
                            Name = "Komodo Bay",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Main St",
                            CountryId = 49,
                            Name = "Sun star",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Lowell St",
                            CountryId = 135,
                            Name = "Lovitz Island",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Maradona St",
                            CountryId = 135,
                            Name = "Lovell",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Gran Via, 15",
                            CountryId = 209,
                            Name = "Ritz Madrid",
                            Rating = 1.5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Rambla, 12",
                            CountryId = 209,
                            Name = "Carlton Barcelona",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 76,
                            Address = "Carballeda, 32",
                            CountryId = 209,
                            Name = "Carlton Bilbao",
                            Rating = 2.5
                        },
                        new
                        {
                            Id = 8,
                            Address = "Motherfucker St.",
                            CountryId = 236,
                            Name = "Trump Mar-a-Lago",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 9,
                            Address = "Tontolaba St.",
                            CountryId = 240,
                            Name = "Maduro's Wonderland",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 10,
                            Address = "Tarantino St.",
                            CountryId = 242,
                            Name = "Virgin Madonna",
                            Rating = 3.5
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
