using HotelListing.API.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HotelListing.API.Data.Configurations;

public class CountryConfiguration : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.HasData(
            new Country { Id = 1, Name = "Afghanistan", Alpha2 = "AF", Alpha3 = "AFG", NumericCode = "0004" },
            new Country { Id = 2, Name = "Albania", Alpha2 = "AL", Alpha3 = "ALB", NumericCode = "0008" },
            new Country { Id = 3, Name = "Algeria", Alpha2 = "DZ", Alpha3 = "DZA", NumericCode = "0012" },
            new Country { Id = 4, Name = "American Samoa", Alpha2 = "AS", Alpha3 = "ASM", NumericCode = "0016" },
            new Country { Id = 5, Name = "Andorra", Alpha2 = "AD", Alpha3 = "AND", NumericCode = "0020" },
            new Country { Id = 6, Name = "Angola", Alpha2 = "AO", Alpha3 = "AGO", NumericCode = "0024" },
            new Country { Id = 7, Name = "Anguilla", Alpha2 = "AI", Alpha3 = "AIA", NumericCode = "0660" },
            new Country { Id = 8, Name = "Antarctica", Alpha2 = "AQ", Alpha3 = "ATA", NumericCode = "0010" },
            new Country { Id = 9, Name = "Antigua and Barbuda", Alpha2 = "AG", Alpha3 = "ATG", NumericCode = "0028" },
            new Country { Id = 10, Name = "Argentina", Alpha2 = "AR", Alpha3 = "ARG", NumericCode = "0032" },
            new Country { Id = 11, Name = "Armenia", Alpha2 = "AM", Alpha3 = "ARM", NumericCode = "0051" },
            new Country { Id = 12, Name = "Aruba", Alpha2 = "AW", Alpha3 = "ABW", NumericCode = "0533" },
            new Country { Id = 13, Name = "Australia", Alpha2 = "AU", Alpha3 = "AUS", NumericCode = "0036" },
            new Country { Id = 14, Name = "Austria", Alpha2 = "AT", Alpha3 = "AUT", NumericCode = "0040" },
            new Country { Id = 15, Name = "Azerbaijan", Alpha2 = "AZ", Alpha3 = "AZE", NumericCode = "0031" },
            new Country { Id = 16, Name = "Bahamas (the)", Alpha2 = "BS", Alpha3 = "BHS", NumericCode = "0044" },
            new Country { Id = 17, Name = "Bahrain", Alpha2 = "BH", Alpha3 = "BHR", NumericCode = "0048" },
            new Country { Id = 18, Name = "Bangladesh", Alpha2 = "BD", Alpha3 = "BGD", NumericCode = "0050" },
            new Country { Id = 19, Name = "Barbados", Alpha2 = "BB", Alpha3 = "BRB", NumericCode = "0052" },
            new Country { Id = 20, Name = "Belarus", Alpha2 = "BY", Alpha3 = "BLR", NumericCode = "0112" },
            new Country { Id = 21, Name = "Belgium", Alpha2 = "BE", Alpha3 = "BEL", NumericCode = "0056" },
            new Country { Id = 22, Name = "Belize", Alpha2 = "BZ", Alpha3 = "BLZ", NumericCode = "0084" },
            new Country { Id = 23, Name = "Benin", Alpha2 = "BJ", Alpha3 = "BEN", NumericCode = "0204" },
            new Country { Id = 24, Name = "Bermuda", Alpha2 = "BM", Alpha3 = "BMU", NumericCode = "0060" },
            new Country { Id = 25, Name = "Bhutan", Alpha2 = "BT", Alpha3 = "BTN", NumericCode = "0064" },
            new Country { Id = 26, Name = "Bolivia (Plurinational State of)", Alpha2 = "BO", Alpha3 = "BOL", NumericCode = "0068" },
            new Country { Id = 27, Name = "Bonaire, Sint Eustatius and Saba", Alpha2 = "BQ", Alpha3 = "BES", NumericCode = "0535" },
            new Country { Id = 28, Name = "Bosnia and Herzegovina", Alpha2 = "BA", Alpha3 = "BIH", NumericCode = "0070" },
            new Country { Id = 29, Name = "Botswana", Alpha2 = "BW", Alpha3 = "BWA", NumericCode = "0072" },
            new Country { Id = 30, Name = "Bouvet Island", Alpha2 = "BV", Alpha3 = "BVT", NumericCode = "0074" },
            new Country { Id = 31, Name = "Brazil", Alpha2 = "BR", Alpha3 = "BRA", NumericCode = "0076" },
            new Country { Id = 32, Name = "British Indian Ocean Territory (the)", Alpha2 = "IO", Alpha3 = "IOT", NumericCode = "0086" },
            new Country { Id = 33, Name = "Brunei Darussalam", Alpha2 = "BN", Alpha3 = "BRN", NumericCode = "0096" },
            new Country { Id = 34, Name = "Bulgaria", Alpha2 = "BG", Alpha3 = "BGR", NumericCode = "0100" },
            new Country { Id = 35, Name = "Burkina Faso", Alpha2 = "BF", Alpha3 = "BFA", NumericCode = "0854" },
            new Country { Id = 36, Name = "Burundi", Alpha2 = "BI", Alpha3 = "BDI", NumericCode = "0108" },
            new Country { Id = 37, Name = "Cabo Verde", Alpha2 = "CV", Alpha3 = "CPV", NumericCode = "0132" },
            new Country { Id = 38, Name = "Cambodia", Alpha2 = "KH", Alpha3 = "KHM", NumericCode = "0116" },
            new Country { Id = 39, Name = "Cameroon", Alpha2 = "CM", Alpha3 = "CMR", NumericCode = "0120" },
            new Country { Id = 40, Name = "Canada", Alpha2 = "CA", Alpha3 = "CAN", NumericCode = "0124" },
            new Country { Id = 41, Name = "Cayman Islands (the)", Alpha2 = "KY", Alpha3 = "CYM", NumericCode = "0136" },
            new Country { Id = 42, Name = "Central African Republic (the)", Alpha2 = "CF", Alpha3 = "CAF", NumericCode = "0140" },
            new Country { Id = 43, Name = "Chad", Alpha2 = "TD", Alpha3 = "TCD", NumericCode = "0148" },
            new Country { Id = 44, Name = "Chile", Alpha2 = "CL", Alpha3 = "CHL", NumericCode = "0152" },
            new Country { Id = 45, Name = "China", Alpha2 = "CN", Alpha3 = "CHN", NumericCode = "0156" },
            new Country { Id = 46, Name = "Christmas Island", Alpha2 = "CX", Alpha3 = "CXR", NumericCode = "0162" },
            new Country { Id = 47, Name = "Cocos (Keeling) Islands (the)", Alpha2 = "CC", Alpha3 = "CCK", NumericCode = "0166" },
            new Country { Id = 48, Name = "Colombia", Alpha2 = "CO", Alpha3 = "COL", NumericCode = "0170" },
            new Country { Id = 49, Name = "Comoros (the)", Alpha2 = "KM", Alpha3 = "COM", NumericCode = "0174" },
            new Country { Id = 50, Name = "Congo (the Democratic Republic of the)", Alpha2 = "CD", Alpha3 = "COD", NumericCode = "0180" },
            new Country { Id = 51, Name = "Congo (the)", Alpha2 = "CG", Alpha3 = "COG", NumericCode = "0178" },
            new Country { Id = 52, Name = "Cook Islands (the)", Alpha2 = "CK", Alpha3 = "COK", NumericCode = "0184" },
            new Country { Id = 53, Name = "Costa Rica", Alpha2 = "CR", Alpha3 = "CRI", NumericCode = "0188" },
            new Country { Id = 54, Name = "Croatia", Alpha2 = "HR", Alpha3 = "HRV", NumericCode = "0191" },
            new Country { Id = 55, Name = "Cuba", Alpha2 = "CU", Alpha3 = "CUB", NumericCode = "0192" },
            new Country { Id = 56, Name = "Curaçao", Alpha2 = "CW", Alpha3 = "CUW", NumericCode = "0531" },
            new Country { Id = 57, Name = "Cyprus", Alpha2 = "CY", Alpha3 = "CYP", NumericCode = "0196" },
            new Country { Id = 58, Name = "Czechia", Alpha2 = "CZ", Alpha3 = "CZE", NumericCode = "0203" },
            new Country { Id = 59, Name = "Côte d'Ivoire", Alpha2 = "CI", Alpha3 = "CIV", NumericCode = "0384" },
            new Country { Id = 60, Name = "Denmark", Alpha2 = "DK", Alpha3 = "DNK", NumericCode = "0208" },
            new Country { Id = 61, Name = "Djibouti", Alpha2 = "DJ", Alpha3 = "DJI", NumericCode = "0262" },
            new Country { Id = 62, Name = "Dominica", Alpha2 = "DM", Alpha3 = "DMA", NumericCode = "0212" },
            new Country { Id = 63, Name = "Dominican Republic (the)", Alpha2 = "DO", Alpha3 = "DOM", NumericCode = "0214" },
            new Country { Id = 64, Name = "Ecuador", Alpha2 = "EC", Alpha3 = "ECU", NumericCode = "0218" },
            new Country { Id = 65, Name = "Egypt", Alpha2 = "EG", Alpha3 = "EGY", NumericCode = "0818" },
            new Country { Id = 66, Name = "El Salvador", Alpha2 = "SV", Alpha3 = "SLV", NumericCode = "0222" },
            new Country { Id = 67, Name = "Equatorial Guinea", Alpha2 = "GQ", Alpha3 = "GNQ", NumericCode = "0226" },
            new Country { Id = 68, Name = "Eritrea", Alpha2 = "ER", Alpha3 = "ERI", NumericCode = "0232" },
            new Country { Id = 69, Name = "Estonia", Alpha2 = "EE", Alpha3 = "EST", NumericCode = "0233" },
            new Country { Id = 70, Name = "Eswatini", Alpha2 = "SZ", Alpha3 = "SWZ", NumericCode = "0748" },
            new Country { Id = 71, Name = "Ethiopia", Alpha2 = "ET", Alpha3 = "ETH", NumericCode = "0231" },
            new Country { Id = 72, Name = "Falkland Islands (the) [Malvinas]", Alpha2 = "FK", Alpha3 = "FLK", NumericCode = "0238" },
            new Country { Id = 73, Name = "Faroe Islands (the)", Alpha2 = "FO", Alpha3 = "FRO", NumericCode = "0234" },
            new Country { Id = 74, Name = "Fiji", Alpha2 = "FJ", Alpha3 = "FJI", NumericCode = "0242" },
            new Country { Id = 75, Name = "Finland", Alpha2 = "FI", Alpha3 = "FIN", NumericCode = "0246" },
            new Country { Id = 76, Name = "France", Alpha2 = "FR", Alpha3 = "FRA", NumericCode = "0250" },
            new Country { Id = 77, Name = "French Guiana", Alpha2 = "GF", Alpha3 = "GUF", NumericCode = "0254" },
            new Country { Id = 78, Name = "French Polynesia", Alpha2 = "PF", Alpha3 = "PYF", NumericCode = "0258" },
            new Country { Id = 79, Name = "French Southern Territories (the)", Alpha2 = "TF", Alpha3 = "ATF", NumericCode = "0260" },
            new Country { Id = 80, Name = "Gabon", Alpha2 = "GA", Alpha3 = "GAB", NumericCode = "0266" },
            new Country { Id = 81, Name = "Gambia (the)", Alpha2 = "GM", Alpha3 = "GMB", NumericCode = "0270" },
            new Country { Id = 82, Name = "Georgia", Alpha2 = "GE", Alpha3 = "GEO", NumericCode = "0268" },
            new Country { Id = 83, Name = "Germany", Alpha2 = "DE", Alpha3 = "DEU", NumericCode = "0276" },
            new Country { Id = 84, Name = "Ghana", Alpha2 = "GH", Alpha3 = "GHA", NumericCode = "0288" },
            new Country { Id = 85, Name = "Gibraltar", Alpha2 = "GI", Alpha3 = "GIB", NumericCode = "0292" },
            new Country { Id = 86, Name = "Greece", Alpha2 = "GR", Alpha3 = "GRC", NumericCode = "0300" },
            new Country { Id = 87, Name = "Greenland", Alpha2 = "GL", Alpha3 = "GRL", NumericCode = "0304" },
            new Country { Id = 88, Name = "Grenada", Alpha2 = "GD", Alpha3 = "GRD", NumericCode = "0308" },
            new Country { Id = 89, Name = "Guadeloupe", Alpha2 = "GP", Alpha3 = "GLP", NumericCode = "0312" },
            new Country { Id = 90, Name = "Guam", Alpha2 = "GU", Alpha3 = "GUM", NumericCode = "0316" },
            new Country { Id = 91, Name = "Guatemala", Alpha2 = "GT", Alpha3 = "GTM", NumericCode = "0320" },
            new Country { Id = 92, Name = "Guernsey", Alpha2 = "GG", Alpha3 = "GGY", NumericCode = "0831" },
            new Country { Id = 93, Name = "Guinea", Alpha2 = "GN", Alpha3 = "GIN", NumericCode = "0324" },
            new Country { Id = 94, Name = "Guinea-Bissau", Alpha2 = "GW", Alpha3 = "GNB", NumericCode = "0624" },
            new Country { Id = 95, Name = "Guyana", Alpha2 = "GY", Alpha3 = "GUY", NumericCode = "0328" },
            new Country { Id = 96, Name = "Haiti", Alpha2 = "HT", Alpha3 = "HTI", NumericCode = "0332" },
            new Country { Id = 97, Name = "Heard Island and McDonald Islands", Alpha2 = "HM", Alpha3 = "HMD", NumericCode = "0334" },
            new Country { Id = 98, Name = "Holy See (the)", Alpha2 = "VA", Alpha3 = "VAT", NumericCode = "0336" },
            new Country { Id = 99, Name = "Honduras", Alpha2 = "HN", Alpha3 = "HND", NumericCode = "0340" },
            new Country { Id = 100, Name = "Hong Kong", Alpha2 = "HK", Alpha3 = "HKG", NumericCode = "0344" },
            new Country { Id = 101, Name = "Hungary", Alpha2 = "HU", Alpha3 = "HUN", NumericCode = "0348" },
            new Country { Id = 102, Name = "Iceland", Alpha2 = "IS", Alpha3 = "ISL", NumericCode = "0352" },
            new Country { Id = 103, Name = "India", Alpha2 = "IN", Alpha3 = "IND", NumericCode = "0356" },
            new Country { Id = 104, Name = "Indonesia", Alpha2 = "ID", Alpha3 = "IDN", NumericCode = "0360" },
            new Country { Id = 105, Name = "Iran (Islamic Republic of)", Alpha2 = "IR", Alpha3 = "IRN", NumericCode = "0364" },
            new Country { Id = 106, Name = "Iraq", Alpha2 = "IQ", Alpha3 = "IRQ", NumericCode = "0368" },
            new Country { Id = 107, Name = "Ireland", Alpha2 = "IE", Alpha3 = "IRL", NumericCode = "0372" },
            new Country { Id = 108, Name = "Isle of Man", Alpha2 = "IM", Alpha3 = "IMN", NumericCode = "0833" },
            new Country { Id = 109, Name = "Israel", Alpha2 = "IL", Alpha3 = "ISR", NumericCode = "0376" },
            new Country { Id = 110, Name = "Italy", Alpha2 = "IT", Alpha3 = "ITA", NumericCode = "0380" },
            new Country { Id = 111, Name = "Jamaica", Alpha2 = "JM", Alpha3 = "JAM", NumericCode = "0388" },
            new Country { Id = 112, Name = "Japan", Alpha2 = "JP", Alpha3 = "JPN", NumericCode = "0392" },
            new Country { Id = 113, Name = "Jersey", Alpha2 = "JE", Alpha3 = "JEY", NumericCode = "0832" },
            new Country { Id = 114, Name = "Jordan", Alpha2 = "JO", Alpha3 = "JOR", NumericCode = "0400" },
            new Country { Id = 115, Name = "Kazakhstan", Alpha2 = "KZ", Alpha3 = "KAZ", NumericCode = "0398" },
            new Country { Id = 116, Name = "Kenya", Alpha2 = "KE", Alpha3 = "KEN", NumericCode = "0404" },
            new Country { Id = 117, Name = "Kiribati", Alpha2 = "KI", Alpha3 = "KIR", NumericCode = "0296" },
            new Country { Id = 118, Name = "Korea (the Democratic People's Republic of)", Alpha2 = "KP", Alpha3 = "PRK", NumericCode = "0408" },
            new Country { Id = 119, Name = "Korea (the Republic of)", Alpha2 = "KR", Alpha3 = "KOR", NumericCode = "0410" },
            new Country { Id = 120, Name = "Kuwait", Alpha2 = "KW", Alpha3 = "KWT", NumericCode = "0414" },
            new Country { Id = 121, Name = "Kyrgyzstan", Alpha2 = "KG", Alpha3 = "KGZ", NumericCode = "0417" },
            new Country { Id = 122, Name = "Lao People's Democratic Republic(the)", Alpha2 = "LA", Alpha3 = "LAO", NumericCode = "0418" },
            new Country { Id = 123, Name = "Latvia", Alpha2 = "LV", Alpha3 = "LVA", NumericCode = "0428" },
            new Country { Id = 124, Name = "Lebanon", Alpha2 = "LB", Alpha3 = "LBN", NumericCode = "0422" },
            new Country { Id = 125, Name = "Lesotho", Alpha2 = "LS", Alpha3 = "LSO", NumericCode = "0426" },
            new Country { Id = 126, Name = "Liberia", Alpha2 = "LR", Alpha3 = "LBR", NumericCode = "0430" },
            new Country { Id = 127, Name = "Libya", Alpha2 = "LY", Alpha3 = "LBY", NumericCode = "0434" },
            new Country { Id = 128, Name = "Liechtenstein", Alpha2 = "LI", Alpha3 = "LIE", NumericCode = "0438" },
            new Country { Id = 129, Name = "Lithuania", Alpha2 = "LT", Alpha3 = "LTU", NumericCode = "0440" },
            new Country { Id = 130, Name = "Luxembourg", Alpha2 = "LU", Alpha3 = "LUX", NumericCode = "0442" },
            new Country { Id = 131, Name = "Macao", Alpha2 = "MO", Alpha3 = "MAC", NumericCode = "0446" },
            new Country { Id = 132, Name = "Madagascar", Alpha2 = "MG", Alpha3 = "MDG", NumericCode = "0450" },
            new Country { Id = 133, Name = "Malawi", Alpha2 = "MW", Alpha3 = "MWI", NumericCode = "0454" },
            new Country { Id = 134, Name = "Malaysia", Alpha2 = "MY", Alpha3 = "MYS", NumericCode = "0458" },
            new Country { Id = 135, Name = "Maldives", Alpha2 = "MV", Alpha3 = "MDV", NumericCode = "0462" },
            new Country { Id = 136, Name = "Mali", Alpha2 = "ML", Alpha3 = "MLI", NumericCode = "0466" },
            new Country { Id = 137, Name = "Malta", Alpha2 = "MT", Alpha3 = "MLT", NumericCode = "0470" },
            new Country { Id = 138, Name = "Marshall Islands (the)", Alpha2 = "MH", Alpha3 = "MHL", NumericCode = "0584" },
            new Country { Id = 139, Name = "Martinique", Alpha2 = "MQ", Alpha3 = "MTQ", NumericCode = "0474" },
            new Country { Id = 140, Name = "Mauritania", Alpha2 = "MR", Alpha3 = "MRT", NumericCode = "0478" },
            new Country { Id = 141, Name = "Mauritius", Alpha2 = "MU", Alpha3 = "MUS", NumericCode = "0480" },
            new Country { Id = 142, Name = "Mayotte", Alpha2 = "YT", Alpha3 = "MYT", NumericCode = "0175" },
            new Country { Id = 143, Name = "Mexico", Alpha2 = "MX", Alpha3 = "MEX", NumericCode = "0484" },
            new Country { Id = 144, Name = "Micronesia (Federated States of)", Alpha2 = "FM", Alpha3 = "FSM", NumericCode = "0583" },
            new Country { Id = 145, Name = "Moldova (the Republic of)", Alpha2 = "MD", Alpha3 = "MDA", NumericCode = "0498" },
            new Country { Id = 146, Name = "Monaco", Alpha2 = "MC", Alpha3 = "MCO", NumericCode = "0492" },
            new Country { Id = 147, Name = "Mongolia", Alpha2 = "MN", Alpha3 = "MNG", NumericCode = "0496" },
            new Country { Id = 148, Name = "Montenegro", Alpha2 = "ME", Alpha3 = "MNE", NumericCode = "0499" },
            new Country { Id = 149, Name = "Montserrat", Alpha2 = "MS", Alpha3 = "MSR", NumericCode = "0500" },
            new Country { Id = 150, Name = "Morocco", Alpha2 = "MA", Alpha3 = "MAR", NumericCode = "0504" },
            new Country { Id = 151, Name = "Mozambique", Alpha2 = "MZ", Alpha3 = "MOZ", NumericCode = "0508" },
            new Country { Id = 152, Name = "Myanmar", Alpha2 = "MM", Alpha3 = "MMR", NumericCode = "0104" },
            new Country { Id = 153, Name = "Namibia", Alpha2 = "NA", Alpha3 = "NAM", NumericCode = "0516" },
            new Country { Id = 154, Name = "Nauru", Alpha2 = "NR", Alpha3 = "NRU", NumericCode = "0520" },
            new Country { Id = 155, Name = "Nepal", Alpha2 = "NP", Alpha3 = "NPL", NumericCode = "0524" },
            new Country { Id = 156, Name = "Netherlands (the)", Alpha2 = "NL", Alpha3 = "NLD", NumericCode = "0528" },
            new Country { Id = 157, Name = "New Caledonia", Alpha2 = "NC", Alpha3 = "NCL", NumericCode = "0540" },
            new Country { Id = 158, Name = "New Zealand", Alpha2 = "NZ", Alpha3 = "NZL", NumericCode = "0554" },
            new Country { Id = 159, Name = "Nicaragua", Alpha2 = "NI", Alpha3 = "NIC", NumericCode = "0558" },
            new Country { Id = 160, Name = "Niger (the)", Alpha2 = "NE", Alpha3 = "NER", NumericCode = "0562" },
            new Country { Id = 161, Name = "Nigeria", Alpha2 = "NG", Alpha3 = "NGA", NumericCode = "0566" },
            new Country { Id = 162, Name = "Niue", Alpha2 = "NU", Alpha3 = "NIU", NumericCode = "0570" },
            new Country { Id = 163, Name = "Norfolk Island", Alpha2 = "NF", Alpha3 = "NFK", NumericCode = "0574" },
            new Country { Id = 164, Name = "Northern Mariana Islands (the)", Alpha2 = "MP", Alpha3 = "MNP", NumericCode = "0580" },
            new Country { Id = 165, Name = "Norway", Alpha2 = "NO", Alpha3 = "NOR", NumericCode = "0578" },
            new Country { Id = 166, Name = "Oman", Alpha2 = "OM", Alpha3 = "OMN", NumericCode = "0512" },
            new Country { Id = 167, Name = "Pakistan", Alpha2 = "PK", Alpha3 = "PAK", NumericCode = "0586" },
            new Country { Id = 168, Name = "Palau", Alpha2 = "PW", Alpha3 = "PLW", NumericCode = "0585" },
            new Country { Id = 169, Name = "Palestine, State of", Alpha2 = "PS", Alpha3 = "PSE", NumericCode = "0275" },
            new Country { Id = 170, Name = "Panama", Alpha2 = "PA", Alpha3 = "PAN", NumericCode = "0591" },
            new Country { Id = 171, Name = "Papua New Guinea", Alpha2 = "PG", Alpha3 = "PNG", NumericCode = "0598" },
            new Country { Id = 172, Name = "Paraguay", Alpha2 = "PY", Alpha3 = "PRY", NumericCode = "0600" },
            new Country { Id = 173, Name = "Peru", Alpha2 = "PE", Alpha3 = "PER", NumericCode = "0604" },
            new Country { Id = 174, Name = "Philippines (the)", Alpha2 = "PH", Alpha3 = "PHL", NumericCode = "0608" },
            new Country { Id = 175, Name = "Pitcairn", Alpha2 = "PN", Alpha3 = "PCN", NumericCode = "0612" },
            new Country { Id = 176, Name = "Poland", Alpha2 = "PL", Alpha3 = "POL", NumericCode = "0616" },
            new Country { Id = 177, Name = "Portugal", Alpha2 = "PT", Alpha3 = "PRT", NumericCode = "0620" },
            new Country { Id = 178, Name = "Puerto Rico", Alpha2 = "PR", Alpha3 = "PRI", NumericCode = "0630" },
            new Country { Id = 179, Name = "Qatar", Alpha2 = "QA", Alpha3 = "QAT", NumericCode = "0634" },
            new Country { Id = 180, Name = "Republic of North Macedonia", Alpha2 = "MK", Alpha3 = "MKD", NumericCode = "0807" },
            new Country { Id = 181, Name = "Romania", Alpha2 = "RO", Alpha3 = "ROU", NumericCode = "0642" },
            new Country { Id = 182, Name = "Russian Federation (the)", Alpha2 = "RU", Alpha3 = "RUS", NumericCode = "0643" },
            new Country { Id = 183, Name = "Rwanda", Alpha2 = "RW", Alpha3 = "RWA", NumericCode = "0646" },
            new Country { Id = 184, Name = "Réunion", Alpha2 = "RE", Alpha3 = "REU", NumericCode = "0638" },
            new Country { Id = 185, Name = "Saint Barthélemy", Alpha2 = "BL", Alpha3 = "BLM", NumericCode = "0652" },
            new Country { Id = 186, Name = "Saint Helena, Ascension and Tristan da Cunha", Alpha2 = "SH", Alpha3 = "SHN", NumericCode = "0654" },
            new Country { Id = 187, Name = "Saint Kitts and Nevis", Alpha2 = "KN", Alpha3 = "KNA", NumericCode = "0659" },
            new Country { Id = 188, Name = "Saint Lucia", Alpha2 = "LC", Alpha3 = "LCA", NumericCode = "0662" },
            new Country { Id = 189, Name = "Saint Martin (French part)", Alpha2 = "MF", Alpha3 = "MAF", NumericCode = "0663" },
            new Country { Id = 190, Name = "Saint Pierre and Miquelon", Alpha2 = "PM", Alpha3 = "SPM", NumericCode = "0666" },
            new Country { Id = 191, Name = "Saint Vincent and the Grenadines", Alpha2 = "VC", Alpha3 = "VCT", NumericCode = "0670" },
            new Country { Id = 192, Name = "Samoa", Alpha2 = "WS", Alpha3 = "WSM", NumericCode = "0882" },
            new Country { Id = 193, Name = "San Marino", Alpha2 = "SM", Alpha3 = "SMR", NumericCode = "0674" },
            new Country { Id = 194, Name = "Sao Tome and Principe", Alpha2 = "ST", Alpha3 = "STP", NumericCode = "0678" },
            new Country { Id = 195, Name = "Saudi Arabia", Alpha2 = "SA", Alpha3 = "SAU", NumericCode = "0682" },
            new Country { Id = 196, Name = "Senegal", Alpha2 = "SN", Alpha3 = "SEN", NumericCode = "0686" },
            new Country { Id = 197, Name = "Serbia", Alpha2 = "RS", Alpha3 = "SRB", NumericCode = "0688" },
            new Country { Id = 198, Name = "Seychelles", Alpha2 = "SC", Alpha3 = "SYC", NumericCode = "0690" },
            new Country { Id = 199, Name = "Sierra Leone", Alpha2 = "SL", Alpha3 = "SLE", NumericCode = "0694" },
            new Country { Id = 200, Name = "Singapore", Alpha2 = "SG", Alpha3 = "SGP", NumericCode = "0702" },
            new Country { Id = 201, Name = "Sint Maarten (Dutch part)", Alpha2 = "SX", Alpha3 = "SXM", NumericCode = "0534" },
            new Country { Id = 202, Name = "Slovakia", Alpha2 = "SK", Alpha3 = "SVK", NumericCode = "0703" },
            new Country { Id = 203, Name = "Slovenia", Alpha2 = "SI", Alpha3 = "SVN", NumericCode = "0705" },
            new Country { Id = 204, Name = "Solomon Islands", Alpha2 = "SB", Alpha3 = "SLB", NumericCode = "0090" },
            new Country { Id = 205, Name = "Somalia", Alpha2 = "SO", Alpha3 = "SOM", NumericCode = "0706" },
            new Country { Id = 206, Name = "South Africa", Alpha2 = "ZA", Alpha3 = "ZAF", NumericCode = "0710" },
            new Country { Id = 207, Name = "South Georgia and the South Sandwich Islands", Alpha2 = "GS", Alpha3 = "SGS", NumericCode = "0239" },
            new Country { Id = 208, Name = "South Sudan", Alpha2 = "SS", Alpha3 = "SSD", NumericCode = "0728" },
            new Country { Id = 209, Name = "Spain", Alpha2 = "ES", Alpha3 = "ESP", NumericCode = "0724" },
            new Country { Id = 210, Name = "Sri Lanka", Alpha2 = "LK", Alpha3 = "LKA", NumericCode = "0144" },
            new Country { Id = 211, Name = "Sudan (the)", Alpha2 = "SD", Alpha3 = "SDN", NumericCode = "0729" },
            new Country { Id = 212, Name = "Suriname", Alpha2 = "SR", Alpha3 = "SUR", NumericCode = "0740" },
            new Country { Id = 213, Name = "Svalbard and Jan Mayen", Alpha2 = "SJ", Alpha3 = "SJM", NumericCode = "0744" },
            new Country { Id = 214, Name = "Sweden", Alpha2 = "SE", Alpha3 = "SWE", NumericCode = "0752" },
            new Country { Id = 215, Name = "Switzerland", Alpha2 = "CH", Alpha3 = "CHE", NumericCode = "0756" },
            new Country { Id = 216, Name = "Syrian Arab Republic", Alpha2 = "SY", Alpha3 = "SYR", NumericCode = "0760" },
            new Country { Id = 217, Name = "Taiwan (Province of China)", Alpha2 = "TW", Alpha3 = "TWN", NumericCode = "0158" },
            new Country { Id = 218, Name = "Tajikistan", Alpha2 = "TJ", Alpha3 = "TJK", NumericCode = "0762" },
            new Country { Id = 219, Name = "Tanzania, United Republic of", Alpha2 = "TZ", Alpha3 = "TZA", NumericCode = "0834" },
            new Country { Id = 220, Name = "Thailand", Alpha2 = "TH", Alpha3 = "THA", NumericCode = "0764" },
            new Country { Id = 221, Name = "Timor-Leste", Alpha2 = "TL", Alpha3 = "TLS", NumericCode = "0626" },
            new Country { Id = 222, Name = "Togo", Alpha2 = "TG", Alpha3 = "TGO", NumericCode = "0768" },
            new Country { Id = 223, Name = "Tokelau", Alpha2 = "TK", Alpha3 = "TKL", NumericCode = "0772" },
            new Country { Id = 224, Name = "Tonga", Alpha2 = "TO", Alpha3 = "TON", NumericCode = "0776" },
            new Country { Id = 225, Name = "Trinidad and Tobago", Alpha2 = "TT", Alpha3 = "TTO", NumericCode = "0780" },
            new Country { Id = 226, Name = "Tunisia", Alpha2 = "TN", Alpha3 = "TUN", NumericCode = "0788" },
            new Country { Id = 227, Name = "Turkey", Alpha2 = "TR", Alpha3 = "TUR", NumericCode = "0792" },
            new Country { Id = 228, Name = "Turkmenistan", Alpha2 = "TM", Alpha3 = "TKM", NumericCode = "0795" },
            new Country { Id = 229, Name = "Turks and Caicos Islands (the)", Alpha2 = "TC", Alpha3 = "TCA", NumericCode = "0796" },
            new Country { Id = 230, Name = "Tuvalu", Alpha2 = "TV", Alpha3 = "TUV", NumericCode = "0798" },
            new Country { Id = 231, Name = "Uganda", Alpha2 = "UG", Alpha3 = "UGA", NumericCode = "0800" },
            new Country { Id = 232, Name = "Ukraine", Alpha2 = "UA", Alpha3 = "UKR", NumericCode = "0804" },
            new Country { Id = 233, Name = "United Arab Emirates (the)", Alpha2 = "AE", Alpha3 = "ARE", NumericCode = "0784" },
            new Country { Id = 234, Name = "United Kingdom of Great Britain and Northern Ireland (the)", Alpha2 = "GB", Alpha3 = "GBR", NumericCode = "0826" },
            new Country { Id = 235, Name = "United States Minor Outlying Islands (the)", Alpha2 = "UM", Alpha3 = "UMI", NumericCode = "0581" },
            new Country { Id = 236, Name = "United States of America (the)", Alpha2 = "US", Alpha3 = "USA", NumericCode = "0840" },
            new Country { Id = 237, Name = "Uruguay", Alpha2 = "UY", Alpha3 = "URY", NumericCode = "0858" },
            new Country { Id = 238, Name = "Uzbekistan", Alpha2 = "UZ", Alpha3 = "UZB", NumericCode = "0860" },
            new Country { Id = 239, Name = "Vanuatu", Alpha2 = "VU", Alpha3 = "VUT", NumericCode = "0548" },
            new Country { Id = 240, Name = "Venezuela (Bolivarian Republic of)", Alpha2 = "VE", Alpha3 = "VEN", NumericCode = "0862" },
            new Country { Id = 241, Name = "Viet Nam", Alpha2 = "VN", Alpha3 = "VNM", NumericCode = "0704" },
            new Country { Id = 242, Name = "Virgin Islands (British)", Alpha2 = "VG", Alpha3 = "VGB", NumericCode = "0092" },
            new Country { Id = 243, Name = "Virgin Islands (U.S.)", Alpha2 = "VI", Alpha3 = "VIR", NumericCode = "0850" },
            new Country { Id = 244, Name = "Wallis and Futuna", Alpha2 = "WF", Alpha3 = "WLF", NumericCode = "0876" },
            new Country { Id = 245, Name = "Western Sahara", Alpha2 = "EH", Alpha3 = "ESH", NumericCode = "0732" },
            new Country { Id = 246, Name = "Yemen", Alpha2 = "YE", Alpha3 = "YEM", NumericCode = "0887" },
            new Country { Id = 247, Name = "Zambia", Alpha2 = "ZM", Alpha3 = "ZMB", NumericCode = "0894" },
            new Country { Id = 248, Name = "Zimbabwe", Alpha2 = "ZW", Alpha3 = "ZWE", NumericCode = "0716" },
            new Country { Id = 249, Name = "Åland Islands", Alpha2 = "AX", Alpha3 = "ALA", NumericCode = "0248" }
            );
    }
}
